version: '3.8'

services:
  postgresql:
    image: bitnami/postgresql:14.17.0-debian-12-r17
    container_name: postgresql
    restart: unless-stopped
    volumes:
      - postgres_data:/bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_DATABASE=${POSTGRES_DB}
      - POSTGRESQL_USERNAME=${POSTGRES_USER}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - jean-project-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api-nest-jean:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-nest-jean
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - jean-project-net
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql:5432/${POSTGRES_DB}

networks:
  jean-project-net:
    driver: bridge

volumes:
  postgres_data:
